"""trade ladders, trailing stops and partial exits

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-03 04:55:47.817351+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("leg", sa.Integer(), nullable=True))
    op.add_column(
        "trade_plans",
        sa.Column("initial_stop_loss", sa.Numeric(precision=18, scale=4), nullable=True),
    )
    op.add_column(
        "trade_plans",
        sa.Column(
            "targets", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column(
        "trade_plans",
        sa.Column(
            "trailing", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.add_column(
        "trade_plans", sa.Column("open_quantity", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "trade_plans", sa.Column("best_price", sa.Numeric(precision=18, scale=4), nullable=True)
    )
    op.add_column(
        "trade_plans", sa.Column("gross_pnl", sa.Numeric(precision=18, scale=4), nullable=True)
    )
    # ### end Alembic commands ###
    # New exit reasons: widen the enum CHECK constraint.
    op.drop_constraint(op.f("ck_trade_plans_exit_reason"), "trade_plans", type_="check")
    op.create_check_constraint(
        op.f("ck_trade_plans_exit_reason"),
        "trade_plans",
        "exit_reason IN ('target', 'stop', 'trailing_stop', 'manual', 'exit_all', "
        "'end_of_day', 'expired', 'cancelled')",
    )
    # Existing trades: one target leg for the whole quantity, original stop as initial.
    op.execute(
        """
        UPDATE trade_plans SET
            initial_stop_loss = stop_loss,
            open_quantity = CASE WHEN status = 'open' THEN quantity ELSE 0 END,
            best_price = entry_price,
            gross_pnl = CASE WHEN realized_pnl IS NOT NULL THEN realized_pnl + charges END,
            targets = CASE WHEN target IS NULL THEN '[]'::jsonb ELSE jsonb_build_array(
                jsonb_build_object(
                    'price', target::text,
                    'quantity', quantity,
                    'status', CASE
                        WHEN status = 'open' THEN 'open'
                        WHEN exit_reason = 'target' THEN 'hit'
                        ELSE 'cancelled' END
                )) END,
            "trailing" = '{"mode": "none", "value": "0"}'::jsonb
        """
    )
    op.execute("UPDATE orders SET leg = 0 WHERE role = 'target'")


def downgrade() -> None:
    op.drop_constraint(op.f("ck_trade_plans_exit_reason"), "trade_plans", type_="check")
    op.create_check_constraint(
        op.f("ck_trade_plans_exit_reason"),
        "trade_plans",
        "exit_reason IN ('target', 'stop', 'manual', 'expired', 'cancelled')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trade_plans", "gross_pnl")
    op.drop_column("trade_plans", "best_price")
    op.drop_column("trade_plans", "open_quantity")
    op.drop_column("trade_plans", "trailing")
    op.drop_column("trade_plans", "targets")
    op.drop_column("trade_plans", "initial_stop_loss")
    op.drop_column("orders", "leg")
    # ### end Alembic commands ###
