"""news feed, alerts and replay (backtest) tables

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-03 05:13:53.181544+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column(
            "kind",
            sa.Enum(
                "news",
                "market",
                "system",
                name="alert_kind",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('news', 'market', 'system')", name=op.f("ck_alerts_alert_kind")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_kind"), "alerts", ["kind"], unique=False)
    op.create_index(op.f("ix_alerts_read"), "alerts", ["read"], unique=False)
    op.create_table(
        "news_items",
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "matched", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("direction", sa.String(length=8), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_items")),
        sa.UniqueConstraint("url", name=op.f("uq_news_items_url")),
    )
    op.create_index("ix_news_items_published_at", "news_items", ["published_at"], unique=False)
    op.create_table(
        "replay_runs",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "done",
                "failed",
                "cancelled",
                name="replay_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "progress", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "report", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'done', 'failed', 'cancelled')",
            name=op.f("ck_replay_runs_replay_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_replay_runs")),
    )
    op.create_index(op.f("ix_replay_runs_status"), "replay_runs", ["status"], unique=False)
    op.create_table(
        "replay_trades",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("message_id", sa.String(length=64), nullable=True),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column("message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "win",
                "loss",
                "breakeven",
                "entry_not_hit",
                "no_data",
                "unresolved",
                "incomplete",
                "not_signal",
                name="replay_outcome",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("instrument_id", sa.UUID(), nullable=True),
        sa.Column("tradingsymbol", sa.String(length=64), nullable=True),
        sa.Column("segment", sa.String(length=16), nullable=True),
        sa.Column(
            "side",
            sa.Enum(
                "BUY", "SELL", name="side", native_enum=False, create_constraint=False, length=32
            ),
            nullable=True,
        ),
        sa.Column(
            "signal", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("entry_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("entry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("exit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "exit_reason",
            sa.Enum(
                "target",
                "stop",
                "trailing_stop",
                "manual",
                "exit_all",
                "end_of_day",
                "expired",
                "cancelled",
                name="exit_reason",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("targets_hit", sa.Integer(), server_default="0", nullable=False),
        sa.Column("gross_pnl", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("charges", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("net_pnl", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("r_multiple", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("mfe", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("mae", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "legs", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "exit_reason IN ('target', 'stop', 'trailing_stop', 'manual', 'exit_all', 'end_of_day', 'expired', 'cancelled')",
            name=op.f("ck_replay_trades_exit_reason"),
        ),
        sa.CheckConstraint(
            "outcome IN ('win', 'loss', 'breakeven', 'entry_not_hit', 'no_data', 'unresolved', 'incomplete', 'not_signal')",
            name=op.f("ck_replay_trades_replay_outcome"),
        ),
        sa.CheckConstraint("side IN ('BUY', 'SELL')", name=op.f("ck_replay_trades_side")),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_replay_trades_instrument_id_instruments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["replay_runs.id"],
            name=op.f("fk_replay_trades_run_id_replay_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["signal_sources.id"],
            name=op.f("fk_replay_trades_source_id_signal_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_replay_trades")),
    )
    op.create_index(op.f("ix_replay_trades_outcome"), "replay_trades", ["outcome"], unique=False)
    op.create_index(op.f("ix_replay_trades_run_id"), "replay_trades", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_replay_trades_run_id"), table_name="replay_trades")
    op.drop_index(op.f("ix_replay_trades_outcome"), table_name="replay_trades")
    op.drop_table("replay_trades")
    op.drop_index(op.f("ix_replay_runs_status"), table_name="replay_runs")
    op.drop_table("replay_runs")
    op.drop_index("ix_news_items_published_at", table_name="news_items")
    op.drop_table("news_items")
    op.drop_index(op.f("ix_alerts_read"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_kind"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
