"""signal details and instrument lookup index

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 02:24:22.972358+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_instruments_name_type_expiry",
        "instruments",
        ["name", "instrument_type", "expiry"],
        unique=False,
    )
    op.add_column(
        "signals",
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signals", "details")
    op.drop_index("ix_instruments_name_type_expiry", table_name="instruments")
    # ### end Alembic commands ###
